### PR TITLE
Callback

### PR DESCRIPTION
**Pull request by katsuyoshi**
add callbacks before/after_create/save/update/destroy

### CODE REVIEW

**Comment by macfanatic** [comment]
Can you rebase this off master to include only the changes that are needed now that #4 is merged in?

**Comment by katsuyoshi** [comment]
I had rebased to d99cc18 .
Is it OK?

**Comment by macfanatic** [comment]
Change set looks better, but the history is a mess.

Ideally this would only show as 1 or 2 commits. Rebasing is dangerous, but not the same as merging.  If done incorrectly our work will disappear, and it requires a force push to github to overwrite the history in your feature branch (safe since it's just you using it).

If nothing else, create a new branch & PR with just the needed changes & we can close this one.

**Comment by katsuyoshi** [comment]
Ok. I'll make a new branch and push PR.

**Comment by katsuyoshi** [comment]
I'll remove my repository first. And refork again. Then I'll make new pull request.

**Comment by katsuyoshi** [comment]
I made a new pull request. #8

**Pull request closed without merging**
